### ISSUE TITLE
Memory consumption benchmark?

### ISSUE THREAD

**Issue by riobard** [xtaci/gaio#1]
@xtaci Thanks a lot for the great work as usual! 👍 

Since this project is primarily aimed at reducing memory consumption and context switching, I'd suggest that it would be very helpful to add a side-by-side comparison of memory usage for the two test cases shown in README.

**Comment by xtaci** [comment]
Thanks, will do, after Chinese Spring Festival.

**Comment by riobard** [comment]
@xtaci Great! Enjoy the vacation and stay safe from the coronavirus! :)
